name: CI Pipeline

on:
  push:
    branches: [main, 'feature/*']
  pull_request:
    branches: [main, 'feature/*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter (optional)
      run: npm run lint
      continue-on-error: true # Will not fail pipeline on linting issues

    - name: Run tests
      run: npm test

    - name: Upload test results (optional)
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/ # Adjust this path based on your test output

